# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Set the API key as an environment variable
ENV SKRAPE_API_KEY=your-key-here

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
